version: "3.8"

services:
  nuxt:
    image: node:16.2.0
    tty: true
    volumes:
      - ./nuxt:/app
    working_dir: /app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - HOST=0.0.0.0